# Generated by Django 5.2.8 on 2025-12-20 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('zona', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuito', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='historial.tablero')),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['tablero', 'fecha'], name='historial_h_tablero_a8e0ba_idx')],
            },
        ),
    ]
