# Generated by Django 5.2.8 on 2025-12-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tablero',
            index=models.Index(fields=['nombre'], name='historial_t_nombre_73bd77_idx'),
        ),
        migrations.AddIndex(
            model_name='tablero',
            index=models.Index(fields=['zona'], name='historial_t_zona_ab7e31_idx'),
        ),
    ]
