# Generated by Django 5.2.8 on 2026-01-09 01:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_tablero_historial_t_nombre_73bd77_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialtarea',
            options={'ordering': ['-fecha', '-creado']},
        ),
        migrations.AddField(
            model_name='historialtarea',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialtarea',
            name='tarea_pedida',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historialtarea',
            name='tarea_pendiente',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historialtarea',
            name='tarea_realizada',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historialtarea',
            name='zona',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='historialtarea',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historialtarea',
            name='tablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='historial.tablero'),
        ),
        migrations.AddIndex(
            model_name='historialtarea',
            index=models.Index(fields=['fecha'], name='historial_h_fecha_26db3b_idx'),
        ),
        migrations.AddIndex(
            model_name='historialtarea',
            index=models.Index(fields=['zona'], name='historial_h_zona_9c230c_idx'),
        ),
    ]
