# Generated by Django 5.2.8 on 2026-01-09 02:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0003_alter_historialtarea_options_historialtarea_creado_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='historialtarea',
            name='historial_h_fecha_26db3b_idx',
        ),
        migrations.RemoveIndex(
            model_name='historialtarea',
            name='historial_h_zona_9c230c_idx',
        ),
        migrations.AddField(
            model_name='historialtarea',
            name='fingerprint',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialtarea',
            name='tablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='historial.tablero'),
        ),
        migrations.AddIndex(
            model_name='historialtarea',
            index=models.Index(fields=['fingerprint'], name='historial_h_fingerp_c8a3a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='historialtarea',
            constraint=models.UniqueConstraint(fields=('tablero', 'fecha', 'fingerprint'), name='uniq_hist_tablero_fecha_fp'),
        ),
    ]
