# Generated by Django 5.2.8 on 2026-01-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0004_remove_historialtarea_historial_h_fecha_26db3b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialtarea',
            name='fingerprint',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
    ]
