# Generated by Django 5.2.8 on 2025-12-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('tablero', models.CharField(max_length=100)),
                ('circuito', models.CharField(blank=True, max_length=100)),
                ('vehiculo', models.CharField(blank=True, max_length=50)),
                ('km_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('km_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tecnicos', models.JSONField(default=list)),
                ('materiales', models.JSONField(default=list)),
                ('tarea_pedida', models.TextField(blank=True)),
                ('tarea_realizada', models.TextField(blank=True)),
                ('tarea_pendiente', models.TextField(blank=True)),
                ('luminaria_equipos', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
