# Generated by Django 5.2.8 on 2025-12-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='conformidad',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='firma_supervisor',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='firma_tecnico',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='firma_tecnico_path',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fotos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
