# Generated by Django 5.2.8 on 2025-12-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordentrabajo_conformidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='conformidad',
        ),
    ]
