# Generated by Django 5.2.8 on 2025-12-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_ordentrabajo_conformidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='km_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
