# Generated by Django 5.2.8 on 2025-12-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordentrabajo_km_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='zona',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
