# Generated by Django 5.2.8 on 2026-01-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordentrabajo_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='ubicacion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
