# Generated by Django 5.2.8 on 2026-01-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_ordentrabajo_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='alcance',
            field=models.CharField(blank=True, default='LUMINARIA', max_length=20),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='estado_tablero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='luminaria_estado',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='resultado',
            field=models.CharField(blank=True, default='COMPLETO', max_length=20),
        ),
    ]
