# Generated by Django 5.2.8 on 2026-01-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordentrabajo_alcance_ordentrabajo_estado_tablero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='codigo_luminaria',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='km_luminaria',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='ramal',
            field=models.CharField(blank=True, choices=[('ACC_NORTE', 'Acc Norte'), ('CAMPANA', 'Campana'), ('PILAR', 'Pilar'), ('ACC_TIGRE', 'Acc Tigre'), ('GRAL_PAZ', 'Gral Paz')], db_index=True, default='', max_length=20),
        ),
    ]
