# Generated by Django 5.2.8 on 2026-02-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_ordentrabajo_codigo_luminaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='codigos_luminarias',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='ramal',
            field=models.CharField(blank=True, choices=[('ACC_NORTE', 'Acc Norte'), ('CAMPANA', 'Campana'), ('PILAR', 'Pilar'), ('ACC_TIGRE', 'Acc Tigre'), ('GRAL_PAZ', 'Gral Paz')], default='', max_length=20),
        ),
    ]
