# Generated by Django 5.2.8 on 2026-03-09 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0005_alter_historialtarea_fingerprint'),
        ('orders', '0009_ordentrabajo_codigos_luminarias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='ramal',
            field=models.CharField(blank=True, choices=[('ACC_NORTE', 'Acc Norte'), ('CAMPANA', 'Campana'), ('PILAR', 'Pilar'), ('ACC_TIGRE', 'Acc Tigre'), ('GRAL_PAZ', 'Gral Paz')], db_index=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='OrdenTrabajoLuminariaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('zona', models.CharField(blank=True, default='', max_length=200)),
                ('circuito', models.CharField(blank=True, default='', max_length=100)),
                ('ramal', models.CharField(blank=True, choices=[('ACC_NORTE', 'Acc Norte'), ('CAMPANA', 'Campana'), ('PILAR', 'Pilar'), ('ACC_TIGRE', 'Acc Tigre'), ('GRAL_PAZ', 'Gral Paz')], db_index=True, default='', max_length=20)),
                ('resultado', models.CharField(blank=True, default='COMPLETO', max_length=20)),
                ('luminaria_estado', models.CharField(blank=True, default='', max_length=20)),
                ('tarea_pedida', models.TextField(blank=True, default='')),
                ('tarea_realizada', models.TextField(blank=True, default='')),
                ('tarea_pendiente', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luminaria_grupos', to='orders.ordentrabajo')),
                ('tablero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ot_luminaria_grupos', to='historial.tablero')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajoLuminariaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('codigo_luminaria', models.CharField(db_index=True, max_length=30)),
                ('km_luminaria', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=6, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.ordentrabajoluminariagrupo')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='ordentrabajoluminariagrupo',
            index=models.Index(fields=['ot'], name='orders_orde_ot_id_57021e_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajoluminariagrupo',
            index=models.Index(fields=['tablero'], name='orders_orde_tablero_a25c42_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajoluminariagrupo',
            index=models.Index(fields=['ramal'], name='orders_orde_ramal_0c2d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajoluminariaitem',
            index=models.Index(fields=['grupo'], name='orders_orde_grupo_i_7ee8f5_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajoluminariaitem',
            index=models.Index(fields=['codigo_luminaria'], name='orders_orde_codigo__00e9ff_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajoluminariaitem',
            index=models.Index(fields=['km_luminaria'], name='orders_orde_km_lumi_f6547d_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordentrabajoluminariaitem',
            constraint=models.UniqueConstraint(fields=('grupo', 'codigo_luminaria'), name='uniq_grupo_codigo_luminaria'),
        ),
    ]
