# Generated by Django 5.2.8 on 2026-03-15 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_ordentrabajo_ramal_ordentrabajoluminariagrupo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='circuito',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='firma_supervisor',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='firma_tecnico',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='firma_tecnico_path',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='luminaria_equipos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tarea_pedida',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tarea_pendiente',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tarea_realizada',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='vehiculo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
